WorkoutTracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("homepage.urls")),
]

homepage/urls.py
from django.urls import path
from . import views
app_name = 'homepage'

urlpatterns = [
    path("", views.HomeView, name="home"),
    path("about/", views.AboutView, name="about"),
    path("blog/", views.BlogView, name="blog"),   # Replace with Wordpress API.
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
import feedparser
import re

def striphtml(data):
        p = re.compile(r'<\/?(?!p)(?!em)\w*\b[^>]*>')
        return p.sub('', data)
    
rssURL = 'https://shawnleemilitary.wordpress.com/feed/'


# Create your views here.
def HomeView(request):
    feed = feedparser.parse(rssURL)
    entries = [{"title" : a["title"], 
                "link" : a["link"], 
                "published": str(a["published_parsed"][0]) + "/" + str(a["published_parsed"][1]) + "/" + str(a["published_parsed"][2]),
                "summary" : re.sub('<span.*?</span>','',a["summary"], flags=re.DOTALL),
                "short_contents" : striphtml(a["content"][0]["value"])[0:500] + "...",
                "full_contents" : a["content"][0]["value"],
               } for a in feed.entries]
    return render(request, "homepage/home.html", {"entries" : entries})


def AboutView(request):
    return render(request, "homepage/about.html")

def BlogView(request):
    feed = feedparser.parse(rssURL)
    entries = [{"title" : a["title"], 
                "link" : a["link"], 
                "published": str(a["published_parsed"][0]) + "/" + str(a["published_parsed"][1]) + "/" + str(a["published_parsed"][2]),
                "summary" : re.sub('<span.*?</span>','',a["summary"], flags=re.DOTALL),
                "short_contents" : striphtml(a["content"][0]["value"])[0:500] + "...",
                "full_contents" : a["content"][0]["value"],
               } for a in feed.entries]
    return render(request, "homepage/blog.html", {"entries" : entries})

Tracker/templates/Tracker/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="description" content='Surviving 545 days of "serving my country"'>
    <meta name="author" content='Shawn Lee'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
      
      <!-- Google Verification -->
      <meta name="google-site-verification" content="4Z24WvpQeHPX5e2P76IzG0EK_PYgBvTMkvUUxYXnI9o" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <!-- My CSS -->
    <link href="{% static 'homepage/images/style.css' %}" rel="stylesheet">
      
    <!-- Fonts -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
      
    <!-- Inline CSS that requires static files: -->
    <style>
        @font-face {
          font-family: 'Permanent Marker';
          src: url("{% static 'homepage/fonts/PermanentMarker-Regular.ttf' %}") format('truetype');
            }
        
        body { 
        padding-top: 90px; 
        }
        /* This is to prevent the navbar from blocking content. */
        * {
            font-family: 'Montserrat';
        }
        
        p {
            color: #283618;
        }
     </style>
     <title>{% block title %}Shawn Lee{% endblock %}</title>
      
     
  </head>

    
    

<body>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- JQuery -->
     <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"></script>
    
    <!-- Content -->
        {% block navbar %}{% endblock %}
        {% block content %}{% endblock %}

</body>
</html>

Tracker/templates/Tracker/navbar.html
{% extends "Tracker/base.html" %}
{% load static %}

{% block navbar %}

<link rel="stylesheet" href="{% static 'homepage/style.css' %}">


<!-- Code to 1. enable dropdown hover and 2. make collapsed navbar white -->
<style>
    @media all and (min-width: 992px) {
	.navbar .nav-item .dropdown-menu{ display: none; }
	.navbar .nav-item:hover .nav-link{   }
	.navbar .nav-item:hover .dropdown-menu{ display: block; }
	.navbar .nav-item .dropdown-menu{ margin-top:0; }
        
}	
</style>

<div class="fixed-top bg-light" id="navbarDiv" data-toggle="affix">
    <!-- Main Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light p-md-3">
      
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'homepage:home' %}">Shawn Lee</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto" style="font-family: 'Montserrat';">
            <li class="nav-item text-center">
              <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
            </li>
            <li class="nav-item text-center">
              <a class="nav-link" href="{% url 'homepage:about' %}">About Me</a>
            </li>
            <li class="nav-item text-center">
              <a class="nav-link" href="https://drive.google.com/file/d/1QwlPVpuzdY-2P3ok2zZQr-eDZ2q3UG5j/view?usp=sharing">Resume</a>
            </li>
            <li class="nav-item text-center">
              <a class="nav-link" href="https://shawnleemilitary.wordpress.com">Blog</a>
            </li>
            <li class="nav-item text-center dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
            External Links
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown" id="socialDropdown">
                
                <li><a class="dropdown-item text-center" href="https://github.com/ShawneeBoy" target="_blank"><img src="https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg" alt="" width="30" height="24" class="d-inline-block align-text-top">Github</a></li>
                <li><a class="dropdown-item text-center" href="https://www.linkedin.com/in/sihyunlee"/ target="_blank"><img src="{% static 'homepage/images/linkedin.svg' %}" alt="" width="30" height="24" class="d-inline-block align-text-top">LinkedIn</a></li>
              </ul>
            </li>
            {% comment %} <li class="nav-item text-center">
              <a class="nav-link" href="{% url 'Tracker:home' %}">Workout Tracker</a>
            </li> {% endcomment %}
          </ul>
        </div>
      </div>
    </nav>
</div>

<script>
    $(".navbar-toggler").click(function () {
    $("nav").toggleClass("bg-light");
    })
</script>


{% endblock %}

homepage/templates/homepage/about.html
{% extends 'homepage/navbar.html' %}
{% load static %}
{% block content %}
    <div class="container container-small">
        <h1 class="display-3 text-center"
            style="font-weight: 700;
                   color: #283618;">About Me</h1>
        <div class="container">
            
        </div>
        <div class="p-5 text-center" style="letter-spacing:0.03em;">
            <img src="{% static 'homepage/images/about_me.jpg' %}"
                 class="img-fluid rounded mx-auto d-block"
                 style="max-width: 60%"
                 alt="Me in uniform!">
            <br>
            <h3 class="text-center" style="font-weight: 700;  color: #283618;">Hi!</h3>
            <br>
            <p>Hey, I'm Shawn. Welcome to my personal portfolio website!</p>
            <p>...no, that's a huge overstatement.</p>
            <p>
                Uh... welcome to the thing that is a conglomeration of crudely constructed HTML, CSS, and JS code snippets that I copy-pasted from StackOverflow and Youtube.
            </p>
            <p>
                I'm not even joking -- that's all that this is. The fancy navbar at the top? 
                 That cool typewriter effect? The pretty animations on my projects?
                 That's all just copy-pasted code that I spent hours tweaking.
            </p>
            <p>Then again, maybe that's really all coding is.</p>
            <hr>
            <p>I'm a freshman at Carnegie Mellon University's School of Computer Science.</p>
            <p>
                I like coding, making music, videography, playing badminton/basketball/guitar/League of Legends (and be terrible at all four), and cultivating deep, trusting relationships with people I like and trust.
            </p>
            <p>
                Feel free to look around my website, but there's not too much else to see (besides my <a href="https://shawnleemilitary.wordpress.com">blog</a>, maybe?). 
                 I literally started web development a few weeks ago. 
                 So if like my navbar suddenly overlaps elements of my site, or like a heading looks really oddly positioned, I hope you give me a break. 
                 This isn't Wordpress or Wix, I'm writing code to try to make this pretty.
            </p>
            <p>
                Again, welcome. If you've read this far, you get a virtual hug from me. :)
            </p>
        </div>
    </div>
{% endblock %}

homepage/templates/homepage/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="description" content='Surviving 545 days of "serving my country"'>
    <meta name="author" content='Shawn Lee'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
      
      <!-- Google Verification -->
      <meta name="google-site-verification" content="4Z24WvpQeHPX5e2P76IzG0EK_PYgBvTMkvUUxYXnI9o" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <!-- My CSS -->
    <link href="{% static 'homepage/style.css' %}" rel="stylesheet">
      
    <!-- Fonts -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
      
    <!-- Inline CSS that requires static files: -->
    <style>
        @font-face {
          font-family: 'Permanent Marker';
          src: url("{% static 'homepage/fonts/PermanentMarker-Regular.ttf' %}") format('truetype');
            }
        
        body { 
        padding-top: 90px; 
        }
        /* This is to prevent the navbar from blocking content. */
        * {
            font-family: 'Montserrat';
        }
        
        p {
            color: #283618;
        }
     </style>
     <title>{% block title %}Shawn Lee{% endblock %}</title>
      
     
  </head>

    
    

<body>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- JQuery -->
     <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"></script>
    
    <!-- Content -->
        {% block navbar %}{% endblock %}
        {% block content %}{% endblock %}

</body>
</html>

homepage/templates/homepage/blog.html
{% extends 'homepage/navbar.html' %}
{% block content %}
    <style>
        .feed-item-title {
            font-weight: 700;
            font-size: 30px;
        }
        
        @media (min-width: 900px) {
            .container-small {
                width: 900px;
            }
        
            .container-large {
                width: 1500px;
            }
        }
        
        .container-small,
        .container-large {
            max-width: 100%;
        }
    </style>
    <div class="container container-small">
        <h1 class="display-3 text-center" style="font-weight: 700;">Blog</h1>
        {% for entry in entries %}
            <div class="p-5 border rounded shadow" style="margin:15px;">
                <h3>{{ entry.title }}</h3>
                <h3>{{ entry.published }}</h3>
                {{ entry.short_contents | safe }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

homepage/templates/homepage/navbar.html
{% extends "homepage/base.html" %}
{% load static %}

{% block navbar %}

<link rel="stylesheet" href="{% static 'homepage/style.css' %}">


<!-- Code to 1. enable dropdown hover and 2. make collapsed navbar white -->
<style>
    @media all and (min-width: 992px) {
	.navbar .nav-item .dropdown-menu{ display: none; }
	.navbar .nav-item:hover .nav-link{   }
	.navbar .nav-item:hover .dropdown-menu{ display: block; }
	.navbar .nav-item .dropdown-menu{ margin-top:0; }
        
}	
</style>

<div class="fixed-top bg-light" id="navbarDiv" data-toggle="affix">
    <!-- Main Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light p-md-3">
      
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'homepage:home' %}">Shawn Lee</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto" style="font-family: 'Montserrat';">
            <li class="nav-item text-center">
              <a class="nav-link" href="#top">Home</a>
            </li>
            <li class="nav-item text-center">
              <a class="nav-link" href="#aboutMe">About Me</a>
            </li>
            <li class="nav-item text-center">
              <a class="nav-link" href="#projects">Projects</a>
            </li>
            <li class="nav-item text-center">
              <a class="nav-link" href="#research">Research</a>
            </li>
            <li class="nav-item text-center">
              <a class="nav-link" href="https://drive.google.com/file/d/1QwlPVpuzdY-2P3ok2zZQr-eDZ2q3UG5j/view?usp=sharing">Resume</a>
            </li>
            <!-- Blog -->
            {% comment %} <li class="nav-item text-center">
              <a class="nav-link" href="https://shawnleemilitary.wordpress.com">Blog</a>
            </li> {% endcomment %}
            <li class="nav-item text-center dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
            External Links
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown" id="socialDropdown">
                
                <li><a class="dropdown-item text-center" href="https://github.com/ShawneeBoy" target="_blank"><img src="https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg" alt="" width="30" height="24" class="d-inline-block align-text-top">Github</a></li>
                <li><a class="dropdown-item text-center" href="https://www.linkedin.com/in/sihyunlee"/ target="_blank"><img src="{% static 'homepage/images/linkedin.svg' %}" alt="" width="30" height="24" class="d-inline-block align-text-top">LinkedIn</a></li>
              </ul>
            </li>
            {% comment %} <li class="nav-item text-center">
              <a class="nav-link" href="{% url 'Tracker:home' %}">Workout Tracker</a>
            </li> {% endcomment %}
          </ul>
        </div>
      </div>
    </nav>
</div>

<script>
    $(".navbar-toggler").click(function () {
    $("nav").toggleClass("bg-light");
    })
</script>


{% endblock %}